require("H_config.plugins-setup")
require("H_config.core.options")
require("H_config.core.keymaps")
require("H_config.core.colorscheme")
require("H_config.plugins.nvim-tree")
require("H_config.plugins.treesitter")
require("H_config.plugins.lualine")
require("H_config.plugins.bufferline")
require("H_config.plugins.lsp_config")
-- require("H_config.plugins.complition")
